# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.12.0 on Sun Dec  4 13:21:39 2022
# Model: Annual Water Yield
import numpy as np
import pandas as pd
import logging
import sys
import csv
import os

import natcap.invest.annual_water_yield as awy
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = { #split args for kc and variable manipulation
    'biophysical_table_path': 'F:/data/biophysical_table_final.csv',
    'demand_table_path': '',
    'depth_to_root_rest_layer_path': 'F:/data/root/BDRICM_M_250m_ll.tif',
    'eto_path': 'F:/data/eto/2021_eto.tif',
    'lulc_path': 'F:/data/lulc/lulcfinalInt.tif',
    'n_workers': '-1',
    'pawc_path': 'F:/data/PAWC/PAWC.tif',
    'precipitation_path': 'F:/precipitation/2021.tif',
    'results_suffix': '',
    'seasonality_constant': '30',
    'sub_watersheds_path': '',
    'valuation_table_path': '',
    'watersheds_path': 'F:/data/watersheds/shp_proyectado_final.shp',
    'workspace_dir': 'F:/data/1',
}
salidas=os.chdir("F:/data/1")
wyield_vol = np.zeros((30), dtype=np.float64)
season = list(np.arange(1,30+1))
with open('/python_script_invest/numbers.csv', 'w', newline='') as csvfile:
  # Create a CSV writer
  writer = csv.writer(csvfile)
  # Write the header row
  writer.writerow(['Kc', 'resultados'])
  for i in season:
#     for j in range(0.8,1.5) loop for KC (still testing)
        args['seasonality_constant'] = str(i)
        awy.execute(args)
        simulation  = pd.read_csv(r"F:\data\1\output\watershed_results_wyield.csv")
        Sim  = simulation['wyield_vol'].values
        kc =str(i)
        writer.writerow([kc,Sim])

'''
if __name__ == '__main__':
    natcap.invest.annual_water_yield.execute(args)
'''

#ID_File = open(PathResults, 'w')
#ID_File.write('Z,Factor-Kc,RMSE\n')
#ID_File.close()
